<br/>
<div class="col-xs-6 col-xs-offset-3">
    <form action="" id="contactForm" method="post">
    <div class="fieldset">
        <ul class="form-list">
            <li class="fields">
                <div class="field">
                    <label for="email" class="required a-left"><em>*</em>Email</label>

                    <div class="input-box">
                        <input name="email" id="email" class="input-text required-entry validate-email" type="email"
                               placeholder="Input Email"/>
                    </div>
                </div>
                <div class="field">
                    <label for="name" class="required"><em>*</em>Name</label>

                    <div class="input-box">
                        <input name="name" id="name" class="input-text required-entry" type="text"
                               placeholder="Input Name"/>
                    </div>
                </div>
            </li>
            <li>
                <label for="telephone">Telephone</label>

                <div class="input-box">
                    <input name="telephone" id="telephone" class="input-text" type="tel"
                           placeholder="Input Telephone"/>
                </div>
            </li>
            <li class="wide">
                <label for="comment" class="required"><em>*</em>Description</label>

                <div class="input-box">
                        <textarea name="comment" id="comment" class="required-entry input-text" cols="5" rows="3"
                                  placeholder="Input Description"></textarea>
                </div>
            </li>
        </ul>
    </div>
    <div class="buttons-set">
        <button type="submit" class="button">Submit</button>
    </div>
</form>
</div>


