<style>
    .carousel-inner > .item > img,
    .carousel-inner > .item > a > img {
        width: 70%;
        margin: auto;
    }
</style>
<?php if (($sliders = $this->getSliderCollection()) && ($sliders->getSize())) {
    //var_dump($sliders->getSize());
?>
<div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        <?php for($i=0; $i<$sliders->getSize(); $i++) {?>
        <li data-target="#myCarousel" data-slide-to="<?php echo $i;?>" <?php if ($i == 0) echo ' class="active"'; ?>></li>
        <?php }?>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
        <?php $j = 0;
        foreach ($sliders->getItems() as $slide) {?>
        <div class="item <?php if ($j == 0) echo ' active'?>">
            <img src="<?php echo $this->getSkinUrl($slide->getImage())?>" alt="<?php echo $slide->getTitle()?>">
            <div class="carousel-caption">
                <h3><?php echo $slide->getTitle()?></h3>
                <p><?php echo $slide->getDescription()?></p>
            </div>
        </div>
        <?php $j++;
        }?>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev" style="background-image: none">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next" style="background-image: none">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>
<br/>
<?php }?>